table 'Calendar Lookup'
	lineageTag: 1d841628-0aa1-4b69-8126-64d6c7b8fe5c

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: b8c62469-dbe9-40f5-b855-bd168437dbf9
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: e8334e9d-6cdf-4fe2-80d4-3d02915df6a0
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7f29ccf6-177a-43f3-bdc1-af9816a5f6be
		summarizeBy: none
		sourceColumn: Start of Week

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 38220dc1-000a-4050-b4a7-f48d64bf1331
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Quarter'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f653492c-351f-491d-8b41-ccab550c86c2
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		lineageTag: adb9ffe8-d986-4031-98ce-8200473e3fe7
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8bd420ca-b9a1-4403-8609-a99ab33ec7ad
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Start of Year'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0b224feb-8303-4561-a415-908fa7fdbf55
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2c200e24-5a21-49b8-ae0a-903e3fc66256
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Short' =
			
			UPPER(
			    LEFT(
			        'Calendar Lookup'[Month Name],
			        3
			    )
			)
		lineageTag: 7b5a2d18-012c-4ca9-a484-b9423d5c9068
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekend = ```
			
			IF(
			    'Calendar Lookup'[Day Name] IN {"Saturday", "Sunday"}, 
			    "Weekend",
			    "Weekday"
			)
			```
		lineageTag: dea7f058-b3a1-4dc0-82d2-3a02f3fd76ff
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: becd7418-92df-43ed-a6a0-be46bbbfd1b3

		level 'Start of Year'
			lineageTag: 5fed4b13-f731-4522-9cb1-cb4b17c73cfa
			column: 'Start of Year'

		level 'Start of Month'
			lineageTag: 661989b5-a00d-492b-bcc6-51b715af6e7c
			column: 'Start of Month'

		level 'Start of Week'
			lineageTag: cd00427d-ef72-4738-a048-0b64bdb3e63d
			column: 'Start of Week'

		level Date
			lineageTag: 1f803225-747b-4b53-bd94-79f1c34b8d1f
			column: Date

	partition 'Calendar Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\OliverSmith\Documents\training\udemy-adventureworks\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Calendar Lookup.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Day Name", "Start of Week", each Date.StartOfWeek([Date], Day.Monday)),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Start of Week", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Start of Month", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Quarter", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Month", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Start of Year", "Year", each Date.Year([Start of Year]), Int64.Type)
				in
				    #"Inserted Year"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

